apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
data:
  DB_HOST: "aws-1-ap-southeast-1.pooler.supabase.com"
  DB_PORT: "6543"
  DB_USER: "postgres.wiabbgkeaetdetnygrge"
  DB_NAME: "postgres"
  ALGORITHM: "HS256"
  