apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote}}
  DB_PORT: {{ .Values.config.dbPort | quote}}
  DB_USER: {{ .Values.config.dbUser | quote}}
  DB_NAME: {{ .Values.config.dbName | quote}}
  ALGORITHM: {{ .Values.config.algorithm | quote}}
  KAFKA_BROKER: {{ .Values.config.kafkaBroker | quote}}