apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote}}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote}}