{
 "title": "new-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Events Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "events_created", "legendFormat": "Events Created" }
   ]
  },
  {
   "title": "Total Registrations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "total_registration", "legendFormat": "Registrations" }
   ]
  },
  {
   "title": "Available Seats by Event",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_available_seats", "legendFormat": "{{event_title}}" }
   ]
  }
 ]
}